// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7aio1HrxQbqiIrmqLNL2Pv2VZMnm2Jzo',
    appId: '1:374918871212:web:6a6d680d6c80dc31a2c709',
    messagingSenderId: '374918871212',
    projectId: 'caredocs-98220',
    authDomain: 'caredocs-98220.firebaseapp.com',
    storageBucket: 'caredocs-98220.firebasestorage.app',
    measurementId: 'G-QFQ7N8JR3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ4-p965Zn9lOoJS2cyFcPddERJ44A3_U',
    appId: '1:374918871212:android:ee0c1c95ce752e43a2c709',
    messagingSenderId: '374918871212',
    projectId: 'caredocs-98220',
    storageBucket: 'caredocs-98220.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjueFVOyUHDp2H6YyccfYTfV-A4OuvBLM',
    appId: '1:374918871212:ios:297bcb9e422bbda7a2c709',
    messagingSenderId: '374918871212',
    projectId: 'caredocs-98220',
    storageBucket: 'caredocs-98220.firebasestorage.app',
    iosBundleId: 'com.example.caredocsApps',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjueFVOyUHDp2H6YyccfYTfV-A4OuvBLM',
    appId: '1:374918871212:ios:297bcb9e422bbda7a2c709',
    messagingSenderId: '374918871212',
    projectId: 'caredocs-98220',
    storageBucket: 'caredocs-98220.firebasestorage.app',
    iosBundleId: 'com.example.caredocsApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7aio1HrxQbqiIrmqLNL2Pv2VZMnm2Jzo',
    appId: '1:374918871212:web:d4c7baad8a7a28afa2c709',
    messagingSenderId: '374918871212',
    projectId: 'caredocs-98220',
    authDomain: 'caredocs-98220.firebaseapp.com',
    storageBucket: 'caredocs-98220.firebasestorage.app',
    measurementId: 'G-P8QNJWNX96',
  );
}
